name: "Geometry multiplayer"

on:
  workflow_dispatch: # Allows you to manually trigger the build from your iPad

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest # Utilizes GitHub's remote Apple environments
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apple Certificate and Profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          # Create temporary keychain variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import credentials from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Create dynamic keychain
          security create-keychain -p "" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -k $KEYCHAIN_PATH -P "$P12_PASSWORD" -A -t cert -f p12
          security set-key-partition-list -S apple-tool:,apple: -s -k "" $KEYCHAIN_PATH

          # Deploy provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Xcode Archive Build
        run: |
          xcodebuild archive \
            -scheme "YourAppScheme" \
            -archivePath $RUNNER_TEMP/YourApp.xcarchive \
            -sdk iphoneos \
            -configuration Release

      - name: Export IPA Binary
        run: |
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/YourApp.xcarchive \
            -exportPath $RUNNER_TEMP/exported_ipa \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA File to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Application-IPA
          path: ${{ runner.temp }}/exported_ipa/*.ipa
